# This is a sample SlipwayDefaultPipeline, This example contains all of the configurable parameters and hints on how to use them.
apiVersion: spinnaker.cloud.transportation.trimble.com/v1alpha1
kind: SlipwayDefaultPipeline
metadata:
  # This is the name of the K8S crd, this name is also used to generate the name of the spinnaker application that is created.
  name: tcx-maintenancerepairservicev1 # unique key (enforced by Spinnaker application)
  namespace: ttc-spinnaker-operator
spec:
  ignoreAppSuffix: true
  disableTrigger: false # Disable pipeline triggers, set to false to re-enable triggers once confident in migration
  # Team and Contacts populate the relevant banners and fields in spinnaker with the contact information.
  team: tcx-amssteel
  contacts:
    productOwners:
      - product_owner@trimble.com
    technicalContacts:
      - primary_technical_contact@trimble.com
      - secondary_technical_contact@trimble.com
  description: |-
    Describe your service here. This description will be accessible in the Spinnaker application object.
  # If a spinnaker application is manged, the spinnaker operator will lock the pipelines it creates so they cannot be updated within the spinnaker UI and keep them in sync with this YAML file.
  # If this is set to false, the operator will only create pipelines and applications that do not exist. It will not update existing pipelines and will not lock them.
  # Set managed to false if you want to be able to make changes in the spinnaker UI to your pipelines after they are generated
  managed: true
  # This controls where deployment notifications are sent, this must be a valid chat webhook.
  googleChatWebhookUrl: https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D
  # The spinnaker operator must have the roles defined here in order to create the pipelines.
  rbac:
    enabled: true
    applicationPermissions:
      read:
        - tcx-amssteel
        - tcx
      write:
        - tcx-amssteel
      execute:
        - tcx-amssteel
    releasePipelineRoles:
      - tcx-amssteel
      - tcx-lower
      - tcx-prod
      - tcx-docker-registry
      # Enabling deployCrd will create a pipeline in this application that deploys this CRD onto the cluster hosting the spinnaker operator. 
  deployCrd:
    # When set to false this will delete the deploy crd pipeline if it exists
    enabled: true
    # The location of this CRD. It is recommended this be located within the application repository. 
    kubernetesManifest:
      bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
      bitbucketProject: TCX-PRODUCT
      bitbucketRepo: trimble.transportation.maintenance.repair-service.v1
      bitbucketSpinnakerAccount: bitbucket-tcx-ci
      manifestPath: spinnaker.yaml
    # The cluster running the ttc-spinnaker-operator. If RBAC is enabled the pipelineRoles key must have a role that can deploy to this cluster. 
    cluster: gke_slipway-prod_us-central1_slipway-tools-gke-central1-04
    # This is the namespace the operator is running in. Will override namespace in the manifest. 
    namespace: ttc-spinnaker-operator
    # The role that can deploy to the cluster above 
    pipelineRoles:
      - tcx-amssteel
      - slipway-admin
  artifacts:
    containerArtifact:
      imageRegistrySpinnakerAccount: docker-registry
      imageRegistrySpinnakerTriggerAccount: tcx-docker-registry
      imageRegistry: tcxcontainers.azurecr.io
      imageRegistryOrganization: tcx
      imageName: maintenancerepairservicev1
      imageTagTriggerRegEx: '^(master-|main-)?[\d\.]+-\w+$'
    kubernetesManifest:
      bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
      bitbucketProject: TCX-PRODUCT
      bitbucketRepo: trimble.transportation.maintenance.repair-service.v1
      bitbucketSpinnakerAccount: bitbucket-tcx-ci
      manifestPath: k8s.yaml
  # Define any jenkins stages that are required. This is flexible and stages can be added or removed as needed.
  jenkinsStages:
    # The key is used as the ID of the stage when binding to environments
    imageValidator:
      # Name is the display name of the stage
      name: Image Validator
      # The jenkins server where this job runs, must exist in spinnaker
      controller: jenkinsV2
      # The Job Name
      job: ImageValidator
      # Any parameters to pass to the job
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
    sonarValidator:
      name: Sonar Validator
      controller: jenkinsV2
      job: SonarValidator
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
    whitesourceValidator:
      name: Whitesource Validator
      controller: jenkinsV2
      job: WhitesourceValidator
      parameters:
        DOCKER_IMAGE: ^{#triggerResolvedArtifactByType("docker/image")["reference"]}
  # Define any jobs that will be used. These jobs can be attached to environments pre or post deployment.
  jobs:
    # The key is used as the ID of the stage when binding to environments
    smokeTesting:
      # Name is the display name of the stage
      name: Smoke Testing
      # Timeout in minutes for the job
      timeout: 20
      # Fail the pipeline if this job fails, if this is set to false the deployment will continue on failure
      failPipeline: false
      # The manifest for this job. Note this currently does not setup any triggers. It is recommended that this job be in the same repository as the main service.
      kubernetesManifest:
        bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
        bitbucketProject: TCX-PRODUCT
        bitbucketRepo: trimble.transportation.maintenance.repair-service.v1
        bitbucketSpinnakerAccount: bitbucket-tcx-ci
        # For paths do not add a leading slash. Example: path/to/file/k8s.yaml
        manifestPath: smoke-test/k8s.yaml
    performanceTesting:
      name: Performance Testing
      timeout: 20
      kubernetesManifest:
        bitbucketFqdn: https://bitbucket.trimble.tools/rest/api/1.0
        bitbucketProject: TCX-PRODUCT
        bitbucketRepo: trimble.transportation.maintenance.repair-service.v1
        bitbucketSpinnakerAccount: bitbucket-tcx-ci
        manifestPath: performance-test/k8s.yaml
  # Define as many environments as needed. Each environment will create a separate spinnaker pipeline
  environments:
    # The key for an environment object acts as its name.
    dev:
      # Define the clusters that belong to this environment. These clusters must exist in spinnaker.
      clusters:
        - tcx-lower-east2
      # Any numbers must be quoted
      parameters:
        namespace: "dev"
        hosts: "maintenancerepairservicev1.dev.trimble-transportation.com"
        keyvault: "tcx-dev-6753214427e7"
        keyvaultSubscriptionId: "c3858f8e-ebe6-4079-a815-8f4d7826f5de"
        keyvaultResourceGroup: "tcxLOWER"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "0"
        maxReplicas: "0"
        apiGatewayHost: "api.dev.slipway.transportation.trimble.com"
      # Restrict the time this environment can be deployed to.
      restrictedExecutionTimeWindow:
        enabled: false
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      # Define if an approval stage will be added before this environment can be deployed.
      requireApproval: false
      # A list of jenkins stages this environment depends on before it can run.
      requiredJenkinsStages: []
      # A list of environments that this environment depends on.
      requiredEnvironments: []
    staging:
      clusters:
        - tcx-staging-east2
        - tcx-staging-west2
      parameters:
        namespace: "staging"
        hosts: "maintenancerepairservicev1.stg.trimble-transportation.com"
        keyvault: "tcx-staging-6753214427e7"
        keyvaultSubscriptionId: "c3858f8e-ebe6-4079-a815-8f4d7826f5de"
        keyvaultResourceGroup: "tcxLOWER"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "0"
        maxReplicas: "0"
        apiGatewayHost: "api.stg.slipway.transportation.trimble.com"
      restrictedExecutionTimeWindow:
        enabled: true
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments:
        - dev
    prod:
      clusters:
        - tcx-prod-east2
        - tcx-prod-west2
      parameters:
        namespace: "prod"
        hosts: "maintenancerepairservicev1.trimble-transportation.com"
        keyvault: "tcx-prod-6753214427e7"
        keyvaultSubscriptionId: "85cae6cd-7015-422a-ae14-d60a136b559b"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        keyvaultResourceGroup: "tcxPROD"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "3"
        maxReplicas: "5"
        apiGatewayHost: "api.slipway.transportation.trimble.com"
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments:
        - staging
    dev-v2:
      # Define the clusters that belong to this environment. These clusters must exist in spinnaker.
      clusters:
        - ttc-dev-eastus2-user
      # Any numbers must be quoted
      parameters:
        namespace: "dev"
        hosts: "maintenancerepairservicev1.dev.trimble-transportation.com"
        keyvault: "tcx-dev-6753214427e7"
        keyvaultSubscriptionId: "c3858f8e-ebe6-4079-a815-8f4d7826f5de"
        keyvaultResourceGroup: "tcxLOWER"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "2"
        maxReplicas: "3"
        apiGatewayHost: "api.dev.v2.ttc.slipway.transportation.trimble.com"
      # Restrict the time this environment can be deployed to.
      restrictedExecutionTimeWindow:
        enabled: false
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      # Define if an approval stage will be added before this environment can be deployed.
      requireApproval: false
      # A list of jenkins stages this environment depends on before it can run.
      requiredJenkinsStages: []
      # A list of environments that this environment depends on.
      requiredEnvironments: []
    staging-v2:
      clusters:
        - ttc-staging-eastus2-user
        - ttc-staging-westus2-user
      parameters:
        namespace: "staging"
        hosts: "maintenancerepairservicev1.stg.trimble-transportation.com"
        keyvault: "tcx-staging-6753214427e7"
        keyvaultSubscriptionId: "c3858f8e-ebe6-4079-a815-8f4d7826f5de"
        keyvaultResourceGroup: "tcxLOWER"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "3"
        maxReplicas: "5"
        apiGatewayHost: "api.stg.v2.ttc.slipway.transportation.trimble.com"
      restrictedExecutionTimeWindow:
        enabled: true
        startHour: 8
        endHour: 17
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments:
        - dev-v2
    prod-v2:
      clusters:
        - ttc-prod-eastus2-user
        - ttc-prod-westus2-user
      parameters:
        namespace: "prod"
        hosts: "maintenancerepairservicev1.trimble-transportation.com"
        keyvault: "tcx-prod-6753214427e7"
        keyvaultSubscriptionId: "85cae6cd-7015-422a-ae14-d60a136b559b"
        keyvaultTenantId: "23235593-4c46-41c1-944b-32a03aab96e6"
        keyvaultResourceGroup: "tcxPROD"
        googleChatWebHookBaseUrl: "https://chat.googleapis.com/v1/spaces/AAAAsnJ1cRg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OIs2NMa_U_qCZOe8UJjQGJZ0L1SPs53jkYRAo-de33A%3D"
        loglevel: "info"
        minReplicas: "3"
        maxReplicas: "5"
        apiGatewayHost: "api.v2.ttc.slipway.transportation.trimble.com"
      # Jobs that run before this environment deploys. Note: jobs will run in all clusters defined for this environment
      preJobs: []
      # Jobs that run after this environment deploys. Note: jobs will run in all clusters defined for this environment
      postJobs: []
      requiredJenkinsStages:
        - imageValidator
        - sonarValidator
        - whitesourceValidator
      requireApproval: true
      requiredEnvironments:
        - staging-v2
